# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1105, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(400, 30, 681, 561))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 381, 251))
        self.tabWidget.setObjectName("tabWidget")
        self.lab1Tab = QtWidgets.QWidget()
        self.lab1Tab.setObjectName("lab1Tab")
        self.label = QtWidgets.QLabel(self.lab1Tab)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.lab1Tab)
        self.textEdit.setGeometry(QtCore.QRect(70, 30, 101, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.lab1Tab)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.lab1Tab)
        self.label_3.setGeometry(QtCore.QRect(200, 30, 21, 16))
        self.label_3.setObjectName("label_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.lab1Tab)
        self.textEdit_2.setGeometry(QtCore.QRect(230, 30, 111, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_4 = QtWidgets.QLabel(self.lab1Tab)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label_4.setObjectName("label_4")
        self.textEdit_3 = QtWidgets.QTextEdit(self.lab1Tab)
        self.textEdit_3.setGeometry(QtCore.QRect(70, 60, 271, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_5 = QtWidgets.QLabel(self.lab1Tab)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 121, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit_4 = QtWidgets.QTextEdit(self.lab1Tab)
        self.textEdit_4.setGeometry(QtCore.QRect(70, 140, 271, 21))
        self.textEdit_4.setObjectName("textEdit_4")
        self.tabWidget.addTab(self.lab1Tab, "")
        self.lab2Tab = QtWidgets.QWidget()
        self.lab2Tab.setObjectName("lab2Tab")
        self.tabWidget.addTab(self.lab2Tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1105, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Начальное приблжение"))
        self.label_2.setText(_translate("MainWindow", "X"))
        self.label_3.setText(_translate("MainWindow", "Y"))
        self.label_4.setText(_translate("MainWindow", "Шаг"))
        self.label_5.setText(_translate("MainWindow", "Итерации"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lab1Tab), _translate("MainWindow", "Lab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lab2Tab), _translate("MainWindow", "Lab 2"))
